name: Validate and Plan Photo Processing Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  TF_WORKING_DIR: infrastructure/terraform

permissions:
  id-token: write
  contents: read

jobs:
  terraform-checks:
    name: Package, Format, Validate and Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Lambda packaging script
        shell: pwsh
        run: ./scripts/package_lambda.ps1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::581816733311:role/event-driven-photo-pipeline-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -no-color

      - name: Upload Lambda package
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: dist/image_processor.zip
